apiVersion: v1
kind: ConfigMap
metadata:
  name: vish-sample
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vish-sample
  annotations:
    reloader.stakater.com/auto: "true"
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 10s"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vish-sample
  template:
    metadata:
      labels:
        app: vish-sample
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: vish-sample
          # image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          image: $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/sample_app_ecr:latest
          resources:
            requests:
              cpu: 1
          volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
      volumes:
        - name: foo
          configMap:
            name: vish-sample