---
apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-test
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: nginx-test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-2048
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: nginx-2048
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: nginx
spec:
  rules:
    - http:
        paths:
          - path: /nginx/*
            backend:
              serviceName: nginx-2048
              servicePort: 80