apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-auth
data:
  personalAccessToken: YOUR-BASE64-PAT-TOKEN
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: pipeline-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azdevops-scaledjob
  labels:
    name: azdo-agents
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          name: azdo-agents
      spec:
        topologySpreadConstraints:
        - maxSkew: 10
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              name: azdo-agents
        nodeSelector:
          karpenter.sh/capacity-type: spot
        containers:
        - name: azdevops-agent-job
          image: 140228208500.dkr.ecr.eu-west-1.amazonaws.com/dot-net-notts:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--once"
          env: # make confifg map
          - name: AZP_URL
            value: "YOUR-AZURE-PORTAL-URL"
          - name: AZP_POOL
            value: "YOUR-AGENT-POOL-NAME"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: pipeline-auth
                key: personalAccessToken
          volumeMounts:
          - mountPath: /var/run/docker.soc
            name: docker-volume
          resources:
            requests:
              cpu: "0.5"
        volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
  pollingInterval: 10
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  maxReplicaCount: 100
  scalingStrategy:
    strategy: "default"               
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: "YOUR-AGENT-POOL-NAME"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZP_TOKEN"
    authenticationRef:
      name: pipeline-trigger-auth