apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  AZP_TOKEN: YOUR-BASE64-PAT-TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            name: azdo-agents
      nodeSelector:
        karpenter.sh/capacity-type: spot
      containers:
      - name: azdevops-agent
        image: 140228208500.dkr.ecr.eu-west-1.amazonaws.com/dot-net-notts:latest
        env:
          - name: AZP_URL
            value: "YOUR-AZURE-PORTAL-URL"
          - name: AZP_KIND
            value: deployment
          - name: AZP_POOL
            value: "YOUR-AGENT-POOL-NAME"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock